server:
  port: 8080
  servlet:
    context-path: /api
spring:
  application:
    name: beisi
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://118.25.157.191:3306/beisi?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8
    username: beisi
    password: 123456
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: is_delete
      logic-delete-value: 1
      logic-not-delete-value: 0
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
    enabled: true
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'user'
      display-name: '用户管理'
      paths-to-match: '/**'
      packages-to-scan: beisi.controller